<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: calculator.proto

namespace Calculator;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>calculator.AdditionRequest</code>
 */
class AdditionRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.calculator.Addition addition = 1;</code>
     */
    protected $addition = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Calculator\Addition $addition
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Calculator::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.calculator.Addition addition = 1;</code>
     * @return \Calculator\Addition|null
     */
    public function getAddition()
    {
        return isset($this->addition) ? $this->addition : null;
    }

    public function hasAddition()
    {
        return isset($this->addition);
    }

    public function clearAddition()
    {
        unset($this->addition);
    }

    /**
     * Generated from protobuf field <code>.calculator.Addition addition = 1;</code>
     * @param \Calculator\Addition $var
     * @return $this
     */
    public function setAddition($var)
    {
        GPBUtil::checkMessage($var, \Calculator\Addition::class);
        $this->addition = $var;

        return $this;
    }

}

