<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: calculator.proto

namespace Calculator;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>calculator.Addition</code>
 */
class Addition extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int32 augend = 1;</code>
     */
    protected $augend = 0;
    /**
     * Generated from protobuf field <code>int32 addend = 2;</code>
     */
    protected $addend = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $augend
     *     @type int $addend
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Calculator::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int32 augend = 1;</code>
     * @return int
     */
    public function getAugend()
    {
        return $this->augend;
    }

    /**
     * Generated from protobuf field <code>int32 augend = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setAugend($var)
    {
        GPBUtil::checkInt32($var);
        $this->augend = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 addend = 2;</code>
     * @return int
     */
    public function getAddend()
    {
        return $this->addend;
    }

    /**
     * Generated from protobuf field <code>int32 addend = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setAddend($var)
    {
        GPBUtil::checkInt32($var);
        $this->addend = $var;

        return $this;
    }

}

