version: '3.7'
services:
  app:
    image: golang:1.16.0-alpine
    volumes:
      - .:/go/src/app
    working_dir: /go/src/app
    command: go run server/index.go server/server.go
    environment:
      MONGO_DSN: "mongodb://root:rootpassword@mongodb:27017"
    ports:
      - "50051:50051"
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data_container:/data/db

volumes:
  mongodb_data_container:
