<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: calculator.proto

namespace Calculator;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>calculator.MaximumResponse</code>
 */
class MaximumResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int32 maximum = 1;</code>
     */
    protected $maximum = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $maximum
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Calculator::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int32 maximum = 1;</code>
     * @return int
     */
    public function getMaximum()
    {
        return $this->maximum;
    }

    /**
     * Generated from protobuf field <code>int32 maximum = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setMaximum($var)
    {
        GPBUtil::checkInt32($var);
        $this->maximum = $var;

        return $this;
    }

}

